name: Playwright Tests

env:
  USER_PASSWORD: ${{ secrets.SECRET_PASSWORD }}
  USER_LOGIN: ${{ secrets.SECRET_LOGIN }}
  BASE_URL: ${{ secrets.BASE_URL }}
  LOGIN_URL: ${{ secrets.LOGIN_URL }}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_smoke_only:
        description: 'Run only smoke tests?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  smoke-test:
    name: Smoke Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.run_smoke_only == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Smoke Tests Only
        run: npx playwright test --grep @smoke
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: smoke-playwright-report
          path: playwright-report/
          retention-days: 30

  full-test:
    name: Full Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: smoke-test
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.run_smoke_only == 'false'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run All Tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: full-playwright-report
          path: playwright-report/
          retention-days: 30
